//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomerceWebASP.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bills()
        {
            this.DetailBIll = new HashSet<DetailBIll>();
        }

        public string idBill { get; set; }
        public string idUser { get; set; }
        public int Shipping { get; set; }
        public int Total { get; set; }
        public string PTTT { get; set; }
        public string status { get; set; }
        public System.DateTime createdAt { get; set; }
        public int totalQty { get; set; }
        public string nameBook { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string note { get; set; }
        public int statusId { get; set; }
        public string voucherCode { get; set; }
        public Nullable<decimal> discount { get; set; }

        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBIll> DetailBIll { get; set; }
        public virtual BillStatus BillStatus { get; set; }
    }
}
