//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomerceWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Bills = new HashSet<Bills>();
        }
    
        public string idUser { get; set; }
        public string idPermission { get; set; }
        public string fullName { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<int> identityCard { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string URLAvatar { get; set; }
        public int phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
