//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomerceWebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int idVoucher { get; set; }
        public decimal discount { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int amount { get; set; }
        public string voucherCode { get; set; }
    }
}
